before:
  hooks:
    - go mod tidy
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
      - arm
    goarm:
      - "7"
archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

dockers:
  - image_templates: ["rskeenan/traindepart-mqtt:{{ .Version }}-amd64"]
    goarch: amd64
    dockerfile: Dockerfile
    use: buildx
    build_flag_templates:
      - --platform=linux/amd64
  - image_templates: [ "rskeenan/traindepart-mqtt:{{ .Version }}-arm64v8" ]
    goarch: arm64
    dockerfile: Dockerfile
    use: buildx
    build_flag_templates:
      - --platform=linux/arm64/v8
  - image_templates: [ "rskeenan/traindepart-mqtt:{{ .Version }}-armv7" ]
    goarch: arm
    goarm: 7
    dockerfile: Dockerfile
    use: buildx
    build_flag_templates:
      - --platform=linux/arm/v7

docker_manifests:
  - name_template: rskeenan/traindepart-mqtt:{{ .Version }}
    image_templates:
      - rskeenan/traindepart-mqtt:{{ .Version }}-amd64
      - rskeenan/traindepart-mqtt:{{ .Version }}-arm64v8
      - rskeenan/traindepart-mqtt:{{ .Version }}-armv7
